### ISSUE TITLE
need offset

### ISSUE THREAD

**Issue by rez1dent3** [Astrotomic/instagram-parser#9]
hi! how give me all user info ( get info with limit and offset ).

**Comment by Gummibeer** [comment]
Hey,
at the moment there is no `offset` implemented. The amount of media entries you get for a user can be changed with

```php
$instagram->setConfig(200, 'media_limit'); // default is 100
```

Cause of the amount of requests this parser creates I recommend to do it in background and not in a sync browser request. The offset part has to be done by you or you add it as a feature to this library.

**Comment by rez1dent3** [comment]
thanks
